# Generated by Django 2.2.3 on 2019-08-14 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20190814_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapinfo',
            name='map',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
