# Generated by Django 2.2.3 on 2019-08-07 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20190721_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapinfo',
            name='port_name',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
