# Generated by Django 2.2.3 on 2019-09-10 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190814_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='carinfo',
            name='for_commute',
            field=models.CharField(default='', max_length=3),
        ),
    ]
