# Generated by Django 2.2.3 on 2019-09-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190910_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='carinfo',
            name='sample',
            field=models.CharField(default='1', max_length=2),
        ),
    ]
