# Generated by Django 2.2.3 on 2019-10-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190925_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='carinfo',
            name='for_index',
            field=models.CharField(default='1', max_length=3),
        ),
    ]
