# Generated by Django 2.2.3 on 2019-07-12 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portinfo', models.CharField(max_length=10)),
                ('portmap', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='CarInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container', models.CharField(max_length=20)),
                ('destination', models.CharField(max_length=20)),
                ('route', models.CharField(max_length=300)),
                ('speed', models.CharField(max_length=10)),
                ('battery', models.CharField(max_length=10)),
                ('communication', models.CharField(max_length=10)),
                ('drivingmode', models.CharField(max_length=5)),
                ('carnumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.MainInfo')),
            ],
        ),
    ]
