# Generated by Django 2.2.3 on 2019-08-14 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190814_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carinfo',
            name='target_x',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='target_y',
            field=models.CharField(default='', max_length=2),
        ),
    ]
