# Generated by Django 2.2.3 on 2019-07-21 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_mapinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MapInfo',
        ),
        migrations.RemoveField(
            model_name='maininfo',
            name='portmap',
        ),
    ]
