# Generated by Django 2.2.3 on 2019-07-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190721_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='carinfo',
            name='now_x',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='now_y',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='target_x',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='target_y',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
