# Generated by Django 2.2.3 on 2019-09-10 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_carinfo_for_commute'),
    ]

    operations = [
        migrations.AddField(
            model_name='carinfo',
            name='now_behavior',
            field=models.CharField(default='', max_length=2),
        ),
    ]
