# Generated by Django 2.2.3 on 2019-09-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_carinfo_now_behavior'),
    ]

    operations = [
        migrations.AddField(
            model_name='carinfo',
            name='car_finish',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='for_commute',
            field=models.CharField(default='1', max_length=3),
        ),
    ]
