# Generated by Django 2.2.3 on 2019-08-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190726_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carinfo',
            name='carnumber',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='MainInfo',
        ),
    ]
