# Generated by Django 2.2.3 on 2019-08-05 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190802_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carinfo',
            name='battery',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='carnumber',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='communication',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='container',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='destination',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='drivingmode',
            field=models.CharField(default='', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='now_x',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='now_y',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='route',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='speed',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='target_x',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='target_y',
            field=models.CharField(default='', max_length=2),
        ),
    ]
