# Generated by Django 2.2.3 on 2019-09-24 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_carinfo_sample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carinfo',
            name='container_id',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.ContainerInfo'),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='pi_id',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.PiInfo'),
        ),
    ]
