# Generated by Django 2.2.3 on 2019-08-06 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190805_1310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carinfo',
            old_name='carnumber',
            new_name='carname',
        ),
    ]
