# Generated by Django 2.2.3 on 2019-08-07 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190806_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carinfo',
            old_name='container',
            new_name='container_number',
        ),
    ]
