# Generated by Django 2.2.3 on 2019-08-07 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190807_1325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carinfo',
            old_name='drivingmode',
            new_name='driving_mode',
        ),
        migrations.AddField(
            model_name='carinfo',
            name='container_company',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='container_product',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='container_shipment_day',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='expected_time',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
