# Generated by Django 2.2.3 on 2019-08-07 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190807_1333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carinfo',
            old_name='carname',
            new_name='car_name',
        ),
    ]
