# Generated by Django 2.2.3 on 2019-08-07 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20190807_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carinfo',
            name='communication',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='driving_mode',
            field=models.CharField(default='', max_length=5, null=True),
        ),
    ]
