# Generated by Django 2.2.3 on 2019-08-07 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20190807_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerInfo',
            fields=[
                ('container_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('destination', models.CharField(max_length=10)),
                ('container_company', models.CharField(max_length=10)),
                ('container_product', models.CharField(max_length=10)),
                ('container_shipment_day', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PiInfo',
            fields=[
                ('pi_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('battery', models.CharField(max_length=10)),
                ('communication', models.CharField(max_length=10)),
                ('car_type', models.CharField(max_length=10)),
                ('picture', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='carinfo',
            name='battery',
        ),
        migrations.RemoveField(
            model_name='carinfo',
            name='communication',
        ),
        migrations.RemoveField(
            model_name='carinfo',
            name='container_company',
        ),
        migrations.RemoveField(
            model_name='carinfo',
            name='container_number',
        ),
        migrations.RemoveField(
            model_name='carinfo',
            name='container_product',
        ),
        migrations.RemoveField(
            model_name='carinfo',
            name='container_shipment_day',
        ),
        migrations.RemoveField(
            model_name='carinfo',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='carinfo',
            name='driving_mode',
        ),
        migrations.RemoveField(
            model_name='carinfo',
            name='expected_time',
        ),
        migrations.RemoveField(
            model_name='carinfo',
            name='route',
        ),
        migrations.RemoveField(
            model_name='carinfo',
            name='speed',
        ),
        migrations.AddField(
            model_name='carinfo',
            name='car_arrive_time',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='car_destination_distance',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='car_now_situation',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='car_route',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='car_speed',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='car_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='now_x',
            field=models.CharField(default='', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='now_y',
            field=models.CharField(default='', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='target_x',
            field=models.CharField(default='', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='target_y',
            field=models.CharField(default='', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='container_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.ContainerInfo'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='pi_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.PiInfo'),
        ),
    ]
