# Generated by Django 2.2.3 on 2019-08-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20190807_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carinfo',
            name='car_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='containerinfo',
            name='container_company',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='containerinfo',
            name='container_product',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='containerinfo',
            name='container_shipment_day',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='containerinfo',
            name='destination',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='piinfo',
            name='battery',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='piinfo',
            name='car_type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='piinfo',
            name='communication',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='piinfo',
            name='picture',
            field=models.URLField(null=True),
        ),
    ]
