# Generated by Django 2.2.3 on 2019-08-07 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20190807_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carinfo',
            name='car_arrive_time',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='car_destination_distance',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='car_now_situation',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='car_speed',
            field=models.CharField(default='', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='container_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.ContainerInfo', unique=True),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='pi_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.PiInfo', unique=True),
        ),
    ]
