# Generated by Django 2.2.3 on 2019-08-07 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20190807_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carinfo',
            name='container_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.ContainerInfo'),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='pi_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.PiInfo'),
        ),
    ]
