# Generated by Django 2.2.3 on 2019-08-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20190808_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carinfo',
            name='now_x',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='now_y',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='target_x',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='target_y',
            field=models.CharField(default='', max_length=2),
        ),
    ]
