# Generated by Django 2.2.3 on 2019-08-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20190808_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carinfo',
            name='car_route',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
