# Generated by Django 2.2.3 on 2019-08-09 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20190808_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carinfo',
            name='now_x',
            field=models.CharField(default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='now_y',
            field=models.CharField(default='1', max_length=2),
        ),
    ]
