# Generated by Django 2.2.3 on 2019-08-09 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20190809_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carinfo',
            name='car_route',
            field=models.CharField(default='1', max_length=10000),
        ),
    ]
