# Generated by Django 2.2.3 on 2019-10-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='picture',
            field=models.URLField(max_length=100, null=True),
        ),
    ]
